<?php
require_once "db_connect.php";

$method = $_SERVER["REQUEST_METHOD"];

if ($method === "OPTIONS") {
    exit;
}

$allowedReportTypes = [
    "Booking Summary",
    "Resource Usage",
    "User Activity",
    "Notification Summary",
    "System Monitoring"
];

$allowedStatuses = [
    "Generated",
    "Pending"
];

function sendResponse($success, $message, $extra = []) {
    echo json_encode(array_merge([
        "success" => $success,
        "message" => $message
    ], $extra));
    exit;
}

function isValidDate($date) {
    $dateObject = DateTime::createFromFormat("Y-m-d", $date);
    return $dateObject && $dateObject->format("Y-m-d") === $date;
}

function validateReport($data) {
    global $allowedReportTypes, $allowedStatuses;

    $reportType = trim($data["reportType"] ?? "");
    $startDate = trim($data["startDate"] ?? "");
    $endDate = trim($data["endDate"] ?? "");
    $status = trim($data["status"] ?? "");
    $generatedBy = trim($data["generatedBy"] ?? "");

    if ($reportType === "" || !in_array($reportType, $allowedReportTypes)) {
        sendResponse(false, "Invalid report type.");
    }

    if ($startDate === "") {
        sendResponse(false, "Start date is required.");
    }

    if (!isValidDate($startDate)) {
        sendResponse(false, "Invalid start date.");
    }

    if ($endDate === "") {
        sendResponse(false, "End date is required.");
    }

    if (!isValidDate($endDate)) {
        sendResponse(false, "Invalid end date.");
    }

    if ($endDate < $startDate) {
        sendResponse(false, "End date cannot be before start date.");
    }

    if ($status === "" || !in_array($status, $allowedStatuses)) {
        sendResponse(false, "Invalid report status.");
    }

    if ($generatedBy === "") {
        sendResponse(false, "Generated by field is required.");
    }

    if (strlen($generatedBy) < 3) {
        sendResponse(false, "Generated by must be at least 3 characters.");
    }

    if (!preg_match("/^[A-Za-z .'-]+$/", $generatedBy)) {
        sendResponse(false, "Generated by can contain letters, spaces, dot, apostrophe and dash only.");
    }

    return [
        "reportType" => $reportType,
        "startDate" => $startDate,
        "endDate" => $endDate,
        "status" => $status,
        "generatedBy" => $generatedBy
    ];
}

/* GET ALL REPORTS */
if ($method === "GET") {
    $sql = "SELECT * FROM admin_reports ORDER BY reportID DESC";
    $result = $conn->query($sql);

    $reports = [];

    while ($row = $result->fetch_assoc()) {
        $reports[] = $row;
    }

    sendResponse(true, "Reports loaded successfully.", [
        "reports" => $reports
    ]);
}

/* CREATE REPORT */
if ($method === "POST") {
    $data = json_decode(file_get_contents("php://input"), true);

    $report = validateReport($data);

    $stmt = $conn->prepare(
        "INSERT INTO admin_reports 
        (reportType, startDate, endDate, status, generatedBy) 
        VALUES (?, ?, ?, ?, ?)"
    );

    $stmt->bind_param(
        "sssss",
        $report["reportType"],
        $report["startDate"],
        $report["endDate"],
        $report["status"],
        $report["generatedBy"]
    );

    if ($stmt->execute()) {
        sendResponse(true, "Report generated successfully.");
    } else {
        sendResponse(false, "Failed to generate report.");
    }
}

/* UPDATE REPORT */
if ($method === "PUT") {
    $data = json_decode(file_get_contents("php://input"), true);

    $reportID = intval($data["reportID"] ?? 0);

    if ($reportID <= 0) {
        sendResponse(false, "Invalid report ID.");
    }

    $report = validateReport($data);

    $stmt = $conn->prepare(
        "UPDATE admin_reports 
        SET reportType = ?, startDate = ?, endDate = ?, status = ?, generatedBy = ?
        WHERE reportID = ?"
    );

    $stmt->bind_param(
        "sssssi",
        $report["reportType"],
        $report["startDate"],
        $report["endDate"],
        $report["status"],
        $report["generatedBy"],
        $reportID
    );

    if ($stmt->execute()) {
        sendResponse(true, "Report updated successfully.");
    } else {
        sendResponse(false, "Failed to update report.");
    }
}

/* DELETE REPORT */
if ($method === "DELETE") {
    $reportID = intval($_GET["id"] ?? 0);

    if ($reportID <= 0) {
        sendResponse(false, "Invalid report ID.");
    }

    $stmt = $conn->prepare("DELETE FROM admin_reports WHERE reportID = ?");
    $stmt->bind_param("i", $reportID);

    if ($stmt->execute()) {
        sendResponse(true, "Report deleted successfully.");
    } else {
        sendResponse(false, "Failed to delete report.");
    }
}

sendResponse(false, "Invalid request method.");
?>